import = [
    "~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
builtin_box_drawing = true
size = 11.0

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.bold_italic]
family = "HackNerdFont"
style = "Bold Italic"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.normal]
family = "HackNerdFont"
style = "Regular"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 1.0

[window.dimensions]
columns = 180
lines = 36

[window.padding]
x = 15
y = 15

[window.position]
x = 0
y = 0
