#  ╔═╗╦  ╔═╗╔═╗╦═╗╦╔╦╗╔╦╗╦ ╦  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠═╣║  ╠═╣║  ╠╦╝║ ║  ║ ╚╦╝  ║  ║ ║║║║╠╣ ║║ ╦	- Config by z0mbi3
#  ╩ ╩╩═╝╩ ╩╚═╝╩╚═╩ ╩  ╩  ╩   ╚═╝╚═╝╝╚╝╚  ╩╚═╝	- https://github.com/gh0stzk/dotfiles
#  General configuration

import:
  - ~/.config/alacritty/rice-colors.yml
  - ~/.config/alacritty/fonts.yml

window:
  padding:
    x: 15
    y: 15
  dimensions:
    columns: 180
    lines: 36
  position:
    x: 0
    y: 0
  decorations: none
  opacity: 1.0
  dynamic_title: true

  history: 10000
  multiplier: 3

font:
  normal:
   family: HackNerdFont
   style: Regular
  bold:
    family: HackNerdFont
    style: Bold
  italic:
    family: HackNerdFont
    style: Italic
  bold_italic:
    family: HackNerdFont
    style: Bold Italic
  size: 11.0
  #offset:
  #  x: 0
  #  y: 0
  #glyph_offset:
  #  x: 0
  #  y: 0
  builtin_box_drawing: true
draw_bold_text_with_bright_colors: true


selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: On
    
  unfocused_hollow: false 
  blink_interval: 550

live_config_reload: true
